### ISSUE TITLE
Unable to use with Java 9 modules

### ISSUE THREAD

**Issue by MikeRee** [kmehrunes/javalin-jwt#1]
Trying to use with Java 9 modules and I'm getting this error trying to compile.

java.lang.module.FindException: Unable to derive module descriptor for C:\Users\mike\.m2\repository\com\github\kmehrunes\javalin-jwt\v0.1-alpha\javalin-jwt-v0.1-alpha.jar
Caused by: java.lang.IllegalArgumentException: javalin.jwt.v0.1.alpha: Invalid module name: '1' is not a Java identifier

**Comment by kmehrunes** [comment]
Honestly I haven't tried it with Java 9 yet, I assumed that everything would work fine since Java is backward compatible. I'll give it a try and let you know.

**Comment by kmehrunes** [comment]
Could you please show how you used it with Java 9? I can't seem to be able to reproduce the issue. In the worst case, you can clone the repository, add a module info file with a valid name and compile the jar from there. It's the only thing I can think of right now.

**Comment by MikeRee** [comment]
I'm using intellij. All I did was take my basic rest project and add a module-info.java to the java src folder. Then Intellij turned all my imports red and I had to click on them and tell IntelliJ to add dependencies to module info.

All dependencies added fine but javalinjwt.* is failing and intellij shows an error: 
![image](https://user-images.githubusercontent.com/753813/46583707-d31ccb80-ca0f-11e8-9d97-92c912efb739.png)

Where is what I have so far in my module-info.java require statements.

module RestApi.api {
    requires javalin;
    requires java.jwt;
    requires slf4j.api;
    requires jdk.incubator.httpclient;
    requires annotations;
}

**Comment by MikeRee** [comment]
I downloaded the source and did a mvn install on it, using the version name in the package and that works.

    <version>0.1</version>

I'm not sure if the -alpha is causing issues or not when referencing it in a Java 9 module. Could you deploy version 0.1 to the maven repository?

**Comment by kmehrunes** [comment]
Oh I see. Thanks for pointing that out. I'll change the name to be module-friendly.
