### ISSUE TITLE
new JWTResponse(token) ERROR with version 0.6

### ISSUE THREAD

**Issue by kgotlelelo-cmd** [kmehrunes/javalin-jwt#10]
app.get("/generate",  context -> {
      // a mock user as an examples
      MockUser mockUser = new MockUser("Mocky McMockface", "admin");

      // generate a token for the user
      String token = provider.generateToken(mockUser);

      // send the JWT response
      context.json(new JWTResponse(token));
});

I get an error when using version 0.6 on new JWTResponse(token) (err=cannot resolve the symbol)

**Comment by kmehrunes** [comment]
JWTResponse is defined in the examples module and is not part of the library, if you wish to use it then you should copy it to your project or create your own with the fields you want
