### ISSUE TITLE
Not able to use GitHub Packages repository with gradle, release 0.7.0

### ISSUE THREAD

**Issue by fedxyz** [kmehrunes/javalin-jwt#14]
Hi,

I am not able to use the new repository that you are using for `javalin-jwt` with gradle.

as dependencies I added:

`implementation 'com.github.kmehrunes:javalin-jwt:0.7.0'`

as repository I added

first:

`maven { url "https://maven.pkg.github.com/kmehrunes/javalin-jwt" }`

and this doesn't work, second reading around here:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry#using-a-published-package

I tried
```
    maven {
        url = uri("https://maven.pkg.github.com/kmehrunes/javalin-jwt")
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
            password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
        }
    }
```
exporting my username and github token before using gradle but nothing, it doesn't work, still:

`com.github.kmehrunes:javalin-jwt:0.7.0 FAILED`

I don't know what I am doing wrong but if I need to export USERNAME and TOKEN every time it seems not so practice.

I have to say that because you created a release the artifact is still available on jitpack, so I was able to use the instructions on jitpack page for v0.7.0

https://jitpack.io/#kmehrunes/javalin-jwt/v0.7

and it worked, more simple imho.

Thanks for the help.

**Comment by fedxyz** [comment]
I was wrong: even the version on jitpack doesn't work, I cannot use it:

with `gradle dependencies` I can see it with no problems `com.github.kmehrunes:javalin-jwt:v0.7` but the library it not available for my project.

**Comment by fedxyz** [comment]
I figured it out: I need a GitHub token with `read:package` scope active and it works. As in the example above you need to setup the credentials on repository declaration.

In practice without a GitHub account you cannot use this package, it was more simple with jitpack imho but I suppose that it is more simple to publish directly from GitHub.

Another suggestion I found is to create `.env` file and in `build.gradle`:

```
def props = new Properties()
file(".env").withInputStream { props.load(it) }
```

and then on repositories section:

```
    maven {
        url = uri("https://maven.pkg.github.com/kmehrunes/javalin-jwt")
        credentials {
            username = props.getProperty('USERNAME')
            password = props.getProperty('TOKEN')
        }
    }
```

**Comment by kmehrunes** [comment]
Hi @fedxyz. I didn't realize that the packages aren't public by default, and based on https://github.com/orgs/community/discussions/26634 it looks like it's not possible right now. I'll move back to JitPack then.

**Comment by kmehrunes** [comment]
Back to using JitPack. Re-open if you had any more issues with this.

**Comment by teemu47** [comment]
First of all, good job on the project 😍 

Could you consider hosting this also somewhere else than on Jitpack? It seems Jitpack is down fairly often.

**Comment by kmehrunes** [comment]
Thanks @teemu47, glad you're finding it useful. 

I thought about moving to Maven Central but stopped out of laziness. I'll try to get that done in the next few days.
