### ISSUE TITLE
Publish to a Maven Repository

### ISSUE THREAD

**Issue by siebl** [kmehrunes/javalin-jwt#15]
While JitPack seems to be an amazingly quick solution to build and publish artifacts on the fly, it is the second day we cannot build.

The build throws following error:
```
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not resolve com.github.kmehrunes.javalin-jwt:javalin-jwt:v0.6.
     Required by:
         project :
      > Could not resolve com.github.kmehrunes.javalin-jwt:javalin-jwt:v0.6.
         > Could not get resource 'https://jitpack.io/com/github/kmehrunes/javalin-jwt/javalin-jwt/v0.6/javalin-jwt-v0.6.pom'.
            > Could not GET 'https://jitpack.io/com/github/kmehrunes/javalin-jwt/javalin-jwt/v0.6/javalin-jwt-v0.6.pom'. Received status code 521 from server: 
```
If the HTTP-Status 521 was not enough: Visiting https://jitpack.io/com/github/kmehrunes/javalin-jwt/ in the browser, displays following message:
```
There seems to be an issue connecting to our servers. Please try again in a few minutes.
```
Locally we can continue to build. But the VMs created in pipelines do not have the advantage of a `mavenLocal()`.

I know it is additional work. But could you publish the artifacts to one of the public repositories? This should add quite some stability.

**Comment by kmehrunes** [comment]
Someone also mentioned that here https://github.com/kmehrunes/javalin-jwt/issues/14#issuecomment-1362733503 so it seems to be a common issue. Will move to a public repository soon.

**Comment by siebl** [comment]
Thank you very much - and great project 💪

**Comment by kmehrunes** [comment]
Just finished releasing 0.7.0 to Central, but it will take a bit longer until it's made available. I'll update the readme later, in the meantime, you can get it using group ID: com.github.kmehrunes, and project ID: javalin-jwt
