### ISSUE TITLE
Support for Javalin 6.x

### ISSUE THREAD

**Issue by fedxyz** [kmehrunes/javalin-jwt#17]
Hi,

Javalin 6.x was released, one of the breaking changes is the removal of `AccessManager`  interface so this extension can't work with it.

Do you plan to upgrade the extension to support 6.x ?
This is the link to the migration guide, [Javalin 5 to 6 migration guide](https://javalin.io/migration-guide-javalin-5-to-6)

Thanks for the help.

**Comment by fedxyz** [comment]
Hi,

about the pull request considering the caveat in the migration guide about the removal of the `AccessManager` this will be used for all the requests (static files or before/after handlers) that is not the same as javalin 5.x.
They consider two examples in the migration guide, it would be nice if you can choose the implementation that you need.

**Comment by kmehrunes** [comment]
Hi Fed. Sorry for the very late reply. I wasn't paying attention to github notifications, and I think github, by default, doesn't send an email unless I was mentioned. I'll take a look at the merge request as soon as possible.

**Comment by fedxyz** [comment]
Thanks @kmehrunes

**Comment by kmehrunes** [comment]
@fedxyz all looks good with the changes, I can't move the repo to javalin org right away since I'm not allowed to create repos there and you already have a fork of javalin-jwt. Can you delete your fork please so that I can  transfer it to you and then you can put it under javalin?

**Comment by fedxyz** [comment]
@kmehrunes Hi, thanks for the reviewing the changes.

I deleted my fork but I think there is a misunderstanding: I am not part of the javalin team, I am just an user of javalin and of javalin-jwt.
I don't know how to transfer javalin-jwt repository to javalin repository.

I think you can reach javalin team on github or write to them on discord. 
I found them on discord when I need to ask some questions about javalin, here there are some links https://javalin.io/community

**Comment by kmehrunes** [comment]
@fedxyz my apologies, from our chat over email I thought you were one of the maintainers of javalin. In that case I'll go ahead with the release as normal.

**Comment by kmehrunes** [comment]
The new version (6.0.0) is now deployed to maven central. Sorry for the delay. Will update the readme tomorrow.

**Comment by fedxyz** [comment]
Thanks @kmehrunes
