### ISSUE TITLE
Make it available in Maven

### ISSUE THREAD

**Issue by yaskor** [kmehrunes/javalin-jwt#2]
Would be real nice if you could add it to your pom without the jitpack workarround.

**Comment by kmehrunes** [comment]
@yaskor Apologies for the very late reply, I totally forgot that this repo even existed. I'm not even sure if people are still using it. If you could confirm that you still need it then I'll do it.

**Comment by yaskor** [comment]
@kmehrunes 
Hi, don't worry, no Im not using it, you can close this. :-)
